import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { seedTemplates } from './seeds/templates'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Début du seeding...')

  // Seed templates first
  await seedTemplates()

  // Créer un utilisateur admin
  const hashedPassword = await bcrypt.hash('admin123', 10)
  const adminUser = await prisma.user.upsert({
    where: { email: 'admin@dzairbox.dz' },
    update: {},
    create: {
      email: 'admin@dzairbox.dz',
      name: 'Admin DzairBox',
      password: hashedPassword,
      role: 'ADMIN',
      phone: '+213 555 123 456',
      city: 'Alger',
    },
  })

  console.log('✅ Utilisateur admin créé:', adminUser.email)

  // Créer un utilisateur normal
  const normalUser = await prisma.user.upsert({
    where: { email: 'user@dzairbox.dz' },
    update: {},
    create: {
      email: 'user@dzairbox.dz',
      name: 'Utilisateur Test',
      password: hashedPassword,
      role: 'USER',
      phone: '+213 555 987 654',
      city: 'Oran',
    },
  })

  console.log('✅ Utilisateur normal créé:', normalUser.email)

  // Entreprises algériennes
  const businesses = [
    // Alger - Restaurants et Cafés
    {
      name: 'Restaurant El Bahia',
      description: 'Restaurant traditionnel algérien spécialisé dans la cuisine kabyle et constantinoise. Ambiance familiale et chaleureuse.',
      category: 'Restaurant',
      address: 'Didouche Mourad, Alger Centre, Alger',
      phone: '+213 21 63 45 78',
      email: 'contact@elbahia.dz',
      facebook: 'elbahia.alger',
      instagram: 'elbahia_alger',
      subdomain: 'elbahia',
      heroImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '11:00-23:00',
        mardi: '11:00-23:00',
        mercredi: '11:00-23:00',
        jeudi: '11:00-23:00',
        vendredi: '14:00-23:00',
        samedi: '11:00-23:00',
        dimanche: '11:00-23:00',
      }),
      services: JSON.stringify(['Livraison', 'Sur place', 'À emporter', 'Wifi gratuit']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Café des Arts',
      description: 'Café culturel proposant des expositions d\'art, concerts live et une carte variée de boissons et pâtisseries.',
      category: 'Café',
      address: 'Rue Larbi Ben M\'hidi, Alger Centre, Alger',
      phone: '+213 21 73 28 91',
      email: 'info@cafedesarts.dz',
      facebook: 'cafedesarts.alger',
      instagram: 'cafe_des_arts',
      tiktok: 'cafedesarts',
      subdomain: 'cafedesarts',
      heroImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:00-22:00',
        mardi: '08:00-22:00',
        mercredi: '08:00-22:00',
        jeudi: '08:00-22:00',
        vendredi: '08:00-22:00',
        samedi: '09:00-23:00',
        dimanche: '09:00-23:00',
      }),
      services: JSON.stringify(['Wifi gratuit', 'Terrasse', 'Événements culturels']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Pâtisserie Les Délices',
      description: 'Pâtisserie traditionnelle et moderne. Gâteaux orientaux, français et personnalisés pour événements.',
      category: 'Pâtisserie',
      address: 'Hydra, Alger',
      heroImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop',
      phone: '+213 21 69 34 56',
      email: 'contact@lesdelices.dz',
      facebook: 'lesdelicesalger',
      instagram: 'les_delices_alger',
      tiktok: 'lesdelices_dz',
      subdomain: 'lesdelices',
      hours: JSON.stringify({
        lundi: '07:00-20:00',
        mardi: '07:00-20:00',
        mercredi: '07:00-20:00',
        jeudi: '07:00-20:00',
        vendredi: '07:00-20:00',
        samedi: '07:00-21:00',
        dimanche: '08:00-20:00',
      }),
      services: JSON.stringify(['Commandes personnalisées', 'Livraison', 'Gâteaux de mariage']),
      isActive: true,
      userId: normalUser.id,
    },

    // Santé et Bien-être
    {
      name: 'Pharmacie Centrale',
      description: 'Pharmacie moderne ouverte 24h/24, garde de nuit, conseil pharmaceutique et vente de produits parapharmaceutiques.',
      category: 'Pharmacie',
      address: 'Place Audin, Alger Centre, Alger',
      phone: '+213 21 64 82 35',
      email: 'pharmacie.centrale@gmail.com',
      facebook: 'pharmaciecentrale',
      subdomain: 'pharmaciecentrale',
      heroImage: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '24h/24',
        mardi: '24h/24',
        mercredi: '24h/24',
        jeudi: '24h/24',
        vendredi: '24h/24',
        samedi: '24h/24',
        dimanche: '24h/24',
      }),
      services: JSON.stringify(['Garde 24h/24', 'Conseil pharmaceutique', 'Parapharmacie']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Clinique Dentaire Sourire',
      description: 'Clinique dentaire moderne équipée des dernières technologies. Orthodontie, implantologie et esthétique dentaire.',
      category: 'Clinique',
      address: 'Dély Ibrahim, Alger',
      phone: '+213 21 91 23 45',
      email: 'contact@cliniquesourire.dz',
      facebook: 'cliniquesourire',
      instagram: 'clinique_sourire',
      subdomain: 'cliniquesourire',
      heroImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-18:00',
        mardi: '09:00-18:00',
        mercredi: '09:00-18:00',
        jeudi: '09:00-18:00',
        vendredi: 'Fermé',
        samedi: '09:00-13:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Orthodontie', 'Implantologie', 'Blanchiment', 'Urgences']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Spa Hammam Wellness',
      description: 'Spa traditionnel et moderne avec hammam, soins du corps, massages et gommage. Espace détente et relaxation.',
      category: 'Spa',
      address: 'Chéraga, Alger',
      phone: '+213 21 36 78 90',
      email: 'contact@hammamwellness.dz',
      facebook: 'hammamwellness',
      instagram: 'hammam_wellness',
      subdomain: 'hammamwellness',
      heroImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '10:00-20:00',
        mardi: '10:00-20:00',
        mercredi: '10:00-20:00',
        jeudi: '10:00-20:00',
        vendredi: '14:00-22:00',
        samedi: '10:00-22:00',
        dimanche: '10:00-20:00',
      }),
      services: JSON.stringify(['Hammam', 'Massage', 'Gommage', 'Soins du visage']),
      isActive: true,
      userId: normalUser.id,
    },

    // Hébergement et Tourisme
    {
      name: 'Hôtel Le Mazafran',
      description: 'Hôtel 4 étoiles avec vue sur la mer, restaurant gastronomique, spa et salles de conférence.',
      category: 'Hôtel',
      address: 'Route de Zéralda, Zeralda, Alger',
      phone: '+213 23 32 55 00',
      email: 'reservation@lemazafran.dz',
      facebook: 'hotelmazafran',
      instagram: 'hotel_mazafran',
      subdomain: 'lemazafran',
      heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '24h/24',
        mardi: '24h/24',
        mercredi: '24h/24',
        jeudi: '24h/24',
        vendredi: '24h/24',
        samedi: '24h/24',
        dimanche: '24h/24',
      }),
      services: JSON.stringify(['Restaurant', 'Spa', 'Piscine', 'Wifi gratuit', 'Parking']),
      isActive: true,
      userId: normalUser.id,
    },

    // Services automobiles
    {
      name: 'Garage Mécanique Auto Pro',
      description: 'Garage automobile spécialisé en mécanique générale, révision, diagnostic électronique et carrosserie.',
      category: 'Garage',
      address: 'Bab Ezzouar, Alger',
      phone: '+213 21 24 56 89',
      email: 'contact@autopro.dz',
      facebook: 'autoproalger',
      subdomain: 'autopro',
      heroImage: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:00-18:00',
        mardi: '08:00-18:00',
        mercredi: '08:00-18:00',
        jeudi: '08:00-18:00',
        vendredi: 'Fermé',
        samedi: '08:00-13:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Mécanique', 'Carrosserie', 'Diagnostic', 'Révision']),
      isActive: true,
      userId: normalUser.id,
    },

    // Beauté et Esthétique
    {
      name: 'Salon de Beauté Nour',
      description: 'Salon de beauté pour femmes : coiffure, maquillage, manucure, pédicure et épilation. Produits professionnels.',
      category: 'Salon de beauté',
      address: 'Ben Aknoun, Alger',
      phone: '+213 21 91 45 67',
      heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&h=600&fit=crop',
      email: 'salonour@gmail.com',
      facebook: 'salonnour',
      instagram: 'salon_nour',
      tiktok: 'salon_nour',
      subdomain: 'salonnour',
      hours: JSON.stringify({
        lundi: '09:00-19:00',
        mardi: '09:00-19:00',
        mercredi: '09:00-19:00',
        jeudi: '09:00-19:00',
        vendredi: '09:00-19:00',
        samedi: '09:00-20:00',
        dimanche: '10:00-18:00',
      }),
      services: JSON.stringify(['Coiffure', 'Maquillage', 'Manucure', 'Pédicure', 'Épilation']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Coiffeur Barber Shop',
      description: 'Salon de coiffure moderne pour hommes. Coupe, rasage traditionnel et soin de la barbe.',
      category: 'Coiffeur',
      address: 'Kouba, Alger',
      phone: '+213 21 28 34 56',
      email: 'barbershop@gmail.com',
      facebook: 'barbershop.alger',
      instagram: 'barbershop_alger',
      subdomain: 'barbershop',
      heroImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-20:00',
        mardi: '09:00-20:00',
        mercredi: '09:00-20:00',
        jeudi: '09:00-20:00',
        vendredi: '14:00-20:00',
        samedi: '09:00-21:00',
        dimanche: '10:00-19:00',
      }),
      services: JSON.stringify(['Coupe homme', 'Rasage', 'Taille barbe', 'Soins capillaires']),
      isActive: true,
      userId: normalUser.id,
    },

    // Oran - Restaurants
    {
      name: 'Restaurant Le Corsaire',
      description: 'Restaurant de fruits de mer avec terrasse panoramique sur la baie d\'Oran. Spécialités méditerranéennes.',
      category: 'Restaurant',
      address: 'Front de Mer, Oran',
      phone: '+213 41 39 12 45',
      email: 'lecorsaire@gmail.com',
      facebook: 'lecorsaire.oran',
      instagram: 'le_corsaire_oran',
      subdomain: 'lecorsaire',
      heroImage: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '12:00-23:00',
        mardi: '12:00-23:00',
        mercredi: '12:00-23:00',
        jeudi: '12:00-23:00',
        vendredi: '12:00-23:00',
        samedi: '12:00-00:00',
        dimanche: '12:00-23:00',
      }),
      services: JSON.stringify(['Terrasse vue mer', 'Parking', 'Wifi gratuit']),
      isActive: true,
      userId: normalUser.id,
    },

    // Services professionnels
    {
      name: 'Cabinet Comptable Expertise',
      description: 'Cabinet d\'expertise comptable et de conseil fiscal. Services aux entreprises et particuliers.',
      category: 'Comptable',
      address: 'Tlemcen, Alger',
      phone: '+213 21 74 56 78',
      email: 'contact@expertise-compta.dz',
      facebook: 'expertise.compta',
      subdomain: 'expertisecompta',
      heroImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:30-17:00',
        mardi: '08:30-17:00',
        mercredi: '08:30-17:00',
        jeudi: '08:30-17:00',
        vendredi: 'Fermé',
        samedi: '09:00-12:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Comptabilité', 'Fiscalité', 'Audit', 'Conseil']),
      isActive: true,
      userId: normalUser.id,
    },

    // Services à domicile - Ménage et Entretien
    {
      name: 'CleanHome Services',
      description: 'Service de ménage professionnel à domicile et en entreprise. Personnel qualifié et produits écologiques.',
      category: 'Ménage',
      address: 'Bir Mourad Raïs, Alger',
      phone: '+213 21 56 78 90',
      email: 'contact@cleanhome.dz',
      facebook: 'cleanhome.alger',
      instagram: 'cleanhome_dz',
      subdomain: 'cleanhome',
      heroImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:00-18:00',
        mardi: '08:00-18:00',
        mercredi: '08:00-18:00',
        jeudi: '08:00-18:00',
        vendredi: '08:00-18:00',
        samedi: '08:00-14:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Ménage à domicile', 'Nettoyage de bureaux', 'Repassage', 'Vitrerie']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Jardinage Pro',
      description: 'Services de jardinage et entretien d\'espaces verts. Taille, tonte, plantation et aménagement paysager.',
      category: 'Jardinage',
      address: 'Draria, Alger',
      phone: '+213 21 38 45 67',
      email: 'contact@jardinagepro.dz',
      facebook: 'jardinagepro',
      instagram: 'jardinage_pro',
      subdomain: 'jardinagepro',
      heroImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '07:00-17:00',
        mardi: '07:00-17:00',
        mercredi: '07:00-17:00',
        jeudi: '07:00-17:00',
        vendredi: '07:00-12:00',
        samedi: '07:00-17:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Tonte de pelouse', 'Taille d\'arbres', 'Plantation', 'Aménagement']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Dépannage Électroménager Express',
      description: 'Réparation et entretien d\'électroménager à domicile. Intervention rapide, toutes marques.',
      category: 'Entretien',
      address: 'Hussein Dey, Alger',
      phone: '+213 21 77 89 01',
      heroImage: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&h=600&fit=crop',
      email: 'express.depannage@gmail.com',
      facebook: 'depannage.express',
      subdomain: 'depannageexpress',
      hours: JSON.stringify({
        lundi: '08:00-19:00',
        mardi: '08:00-19:00',
        mercredi: '08:00-19:00',
        jeudi: '08:00-19:00',
        vendredi: '08:00-19:00',
        samedi: '09:00-17:00',
        dimanche: 'Sur rendez-vous',
      }),
      services: JSON.stringify(['Réparation', 'Entretien', 'Dépannage urgent', 'Pièces détachées']),
      isActive: true,
      userId: normalUser.id,
    },

    // Artisanat et Décoration
    {
      name: 'Artisanat Algérien',
      description: 'Boutique d\'artisanat traditionnel algérien : poterie, tapis, bijoux berbères et cuir travaillé.',
      category: 'Artisanat',
      address: 'Casbah, Alger',
      phone: '+213 21 62 34 56',
      email: 'artisanat.algerien@gmail.com',
      facebook: 'artisanat.algerien',
      instagram: 'artisanat_algerien',
      subdomain: 'artisanatalgerien',
      heroImage: 'https://images.unsplash.com/photo-1582053433616-25df3f888a87?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-18:00',
        mardi: '09:00-18:00',
        mercredi: '09:00-18:00',
        jeudi: '09:00-18:00',
        vendredi: '09:00-12:00',
        samedi: '09:00-18:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Produits artisanaux', 'Commandes personnalisées', 'Export']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Déco Maison',
      description: 'Magasin de décoration d\'intérieur moderne et traditionnel. Conseil en aménagement et décoration.',
      category: 'Décoration',
      address: 'Rouiba, Alger',
      phone: '+213 21 85 67 89',
      email: 'contact@decomaison.dz',
      facebook: 'deco.maison.alger',
      instagram: 'deco_maison_dz',
      subdomain: 'decomaison',
      heroImage: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-18:00',
        mardi: '09:00-18:00',
        mercredi: '09:00-18:00',
        jeudi: '09:00-18:00',
        vendredi: 'Fermé',
        samedi: '09:00-19:00',
        dimanche: '10:00-17:00',
      }),
      services: JSON.stringify(['Décoration intérieure', 'Conseil en aménagement', 'Livraison']),
      isActive: true,
      userId: normalUser.id,
    },

    // Éducation et Formation
    {
      name: 'Auto-École Conduite Sûre',
      description: 'Auto-école agréée proposant formation permis B, conduite accompagnée et stages de perfectionnement.',
      category: 'Auto-école',
      address: 'El Biar, Alger',
      phone: '+213 21 92 34 56',
      email: 'conduitesure@gmail.com',
      facebook: 'conduitesure',
      instagram: 'conduite_sure',
      subdomain: 'conduitesure',
      heroImage: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:00-18:00',
        mardi: '08:00-18:00',
        mercredi: '08:00-18:00',
        jeudi: '08:00-18:00',
        vendredi: 'Fermé',
        samedi: '08:00-13:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Permis B', 'Conduite accompagnée', 'Code en ligne']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Centre de Formation Pro Skills',
      description: 'Centre de formation professionnelle en informatique, langues et gestion. Certifications reconnues.',
      category: 'Formation',
      address: 'Bordj El Kiffan, Alger',
      phone: '+213 21 88 90 12',
      email: 'contact@proskills.dz',
      facebook: 'proskills.dz',
      instagram: 'pro_skills_dz',
      subdomain: 'proskills',
      heroImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:30-17:30',
        mardi: '08:30-17:30',
        mercredi: '08:30-17:30',
        jeudi: '08:30-17:30',
        vendredi: '08:30-12:00',
        samedi: '08:30-17:30',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Formation informatique', 'Cours de langues', 'Formations certifiantes']),
      isActive: true,
      userId: normalUser.id,
    },

    // Sport et Fitness
    {
      name: 'Salle de Sport FitZone',
      description: 'Salle de musculation et fitness moderne avec cours collectifs, coach personnel et espace cardio.',
      category: 'Salle de sport',
      address: 'Les Sources, Alger',
      phone: '+213 21 76 54 32',
      email: 'contact@fitzone.dz',
      facebook: 'fitzone.alger',
      instagram: 'fitzone_alger',
      tiktok: 'fitzone_dz',
      youtube: 'FitZoneAlger',
      subdomain: 'fitzone',
      heroImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '06:00-22:00',
        mardi: '06:00-22:00',
        mercredi: '06:00-22:00',
        jeudi: '06:00-22:00',
        vendredi: '08:00-20:00',
        samedi: '08:00-20:00',
        dimanche: '09:00-18:00',
      }),
      services: JSON.stringify(['Musculation', 'Cardio', 'Cours collectifs', 'Coach personnel']),
      isActive: true,
      userId: normalUser.id,
    },

    // Commerce
    {
      name: 'Librairie El Maarifa',
      description: 'Grande librairie proposant livres en arabe, français et anglais, fournitures scolaires et articles de bureau.',
      heroImage: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&h=600&fit=crop',
      category: 'Librairie',
      address: 'Belcourt, Alger',
      phone: '+213 21 63 78 90',
      email: 'elmaarifa@gmail.com',
      facebook: 'elmaarifa',
      subdomain: 'elmaarifa',
      hours: JSON.stringify({
        lundi: '08:30-19:00',
        mardi: '08:30-19:00',
        mercredi: '08:30-19:00',
        jeudi: '08:30-19:00',
        vendredi: '08:30-12:00',
        samedi: '08:30-19:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Commandes spéciales', 'Livraison', 'Papeterie']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Boutique Mode Élégance',
      description: 'Boutique de prêt-à-porter féminin et accessoires. Collections modernes et traditionnelles.',
      category: 'Vêtements',
      address: 'Bab Ezzouar, Alger',
      phone: '+213 21 24 67 89',
      email: 'elegance@gmail.com',
      facebook: 'elegance.alger',
      instagram: 'elegance_alger',
      tiktok: 'elegance_dz',
      subdomain: 'elegance',
      heroImage: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-19:00',
        mardi: '09:00-19:00',
        mercredi: '09:00-19:00',
        jeudi: '09:00-19:00',
        vendredi: '09:00-19:00',
        samedi: '09:00-20:00',
        dimanche: '10:00-18:00',
      }),
      services: JSON.stringify(['Retouches', 'Conseil en style', 'Livraison']),
      isActive: true,
      userId: normalUser.id,
    },

    // Services créatifs
    {
      name: 'Studio Photo Vision',
      description: 'Studio de photographie professionnelle : portraits, événements, produits et mariages.',
      category: 'Photographe',
      address: 'Hydra, Alger',
      phone: '+213 21 69 45 67',
      email: 'contact@studiovision.dz',
      facebook: 'studiovision.alger',
      instagram: 'studio_vision',
      subdomain: 'studiovision',
      heroImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '09:00-18:00',
        mardi: '09:00-18:00',
        mercredi: '09:00-18:00',
        jeudi: '09:00-18:00',
        vendredi: 'Fermé',
        samedi: '10:00-17:00',
        dimanche: 'Sur rendez-vous',
      }),
      services: JSON.stringify(['Portrait', 'Mariage', 'Événements', 'Photo produit']),
      isActive: true,
      userId: normalUser.id,
    },
    {
      name: 'Imprimerie Rapide',
      description: 'Imprimerie et reprographie : cartes de visite, flyers, affiches, reliure et impression grand format.',
      category: 'Imprimerie',
      address: 'Bachdjerrah, Alger',
      phone: '+213 21 75 89 01',
      email: 'contact@imprimerierapide.dz',
      facebook: 'imprimerie.rapide',
      subdomain: 'imprimerierapide',
      heroImage: 'https://images.unsplash.com/photo-1561489401-fc2876ffe19c?w=800&h=600&fit=crop',
      hours: JSON.stringify({
        lundi: '08:00-18:00',
        mardi: '08:00-18:00',
        mercredi: '08:00-18:00',
        jeudi: '08:00-18:00',
        vendredi: '08:00-12:00',
        samedi: '08:00-17:00',
        dimanche: 'Fermé',
      }),
      services: JSON.stringify(['Impression', 'Reprographie', 'Reliure', 'Grand format']),
      isActive: true,
      userId: normalUser.id,
    },
  ]

  console.log('📝 Création des entreprises...')

  for (const business of businesses) {
    await prisma.business.upsert({
      where: { subdomain: business.subdomain },
      update: {},
      create: business,
    })
    console.log(`✅ Entreprise créée: ${business.name}`)
  }

  console.log('🎉 Seeding terminé avec succès!')
  console.log(`📊 Total: ${businesses.length} entreprises créées`)
  console.log('\n🔐 Identifiants de connexion:')
  console.log('   Admin: admin@dzairbox.dz / admin123')
  console.log('   User:  user@dzairbox.dz / admin123')
}

main()
  .catch((e) => {
    console.error('❌ Erreur lors du seeding:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
